version: '3.7'
services:
    php:
        volumes:
            - './apps/ouimiam/:/usr/src/app'
    nginx:
        volumes:
            - './apps/ouimiam/public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '${NGINX_PORT}:80'
    yarn:
        volumes:
            - './apps/ouimiam/:/usr/src/app'
