# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\HungryUser:
          algorithm: bcrypt
    providers:
        hungry_user_provider:
            entity:
                class: AppBundle:HungryUser
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous: true
            provider: hungry_user_provider
            form_login:
                check_path: user_login
                login_path: user_login
            logout:
                path: security_logout
                target: home

    access_control:
        - { path: ^/account/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account, roles: ROLE_USER }