easy_admin:
    entities:
        BaseIngredient:
            class: App\Entity\BaseIngredient
            list:
                fields:
                    - id
                    - name
            form:
                fields:
                    - id
                    - name