easy_admin:
    entities:
        HungryUser:
            class: App\Entity\HungryUser
            list:
                fields:
                    - id
                    - username
                    - email
            form:
                fields:
                    - id
                    - username
                    - email
                    - password
                    - roles
                    - avatar