easy_admin:
    entities:
        RecipeCollection:
            class: App\Entity\RecipeCollection
            list:
                fields:
                    - id
                    - name
            form:
                fields:
                    - id
                    - name