easy_admin:
    entities:
        Recipe:
            class: App\Entity\Recipe
            list:
                fields:
                    - id
                    - { property: 'image', type: 'image', base_path: '%app.path.recipe_images%' }
                    - name
                    - user
                    - description
                    - ingredients
                    - collections
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
                    - name
                    - user
                    - description
                    - cookingSteps
                    - { property: 'ingredients', type: 'easyadmin_autocomplete', type_options: { by_reference: false } }
                    - { property: collections, type_options: { by_reference: false } }