easy_admin:
    entities:
        RecipeCollection:
            class: App\Entity\RecipeCollection
            list:
                fields:
                    - id
                    - name
                    - user
                    - description
                    - recipes
            form:
                fields:
                    - name
                    - user
                    - description
                    - {property: recipes, type_options: { by_reference: false }}