easy_admin:
    entities:
        Unit:
            class: App\Entity\Unit
            list:
                fields:
                    - id
                    - name
            show:
                fields:
                    - id
                    - name
            form:
                fields:
                    - name